### ISSUE TITLE
ER diagram

### ISSUE THREAD

**Issue by inesmersak** [tinemakovecki/Drinks-and-things#1]
Pregledala sem vajin ER diagram, ki mi zaenkrat še ne izgleda pravilno. Med večina entitetami manjkajo imena relacij, dvakrat se ponovi entiteta _vrsta pijače_ (enkrat v množini, ampak entitete vedno pišemo v ednini). 

Iz trenutnega diagrama ne morem razbrati, kakšna zasnova baze je bila mišljena, zato prosim, da ER diagram dopolnita (in osmislita). Dobro premislita, kaj bi bile smiselne entitete; trenutno izgleda, kot da želita imeti hrano in pijačo kot svojo entiteto, pa potem še pivo in vino kot podvrsti entitete pijača, ki pa skupaj ne pokrijeta nujno vseh pijač. 

Če se vama pri premisleku zatakne, mi seveda lahko pišeta (kar sem).

Ko bosta končala, prosim še, da ER diagram dodata v `README.md`, in sicer tako, da dodata sledečo kodo:

```Markdown
![ER diagram](diagram.png)
```

**Comment by tinemakovecki** [comment]
commit e87e2cf
