### ISSUE TITLE
Nevarna SQL poizvedba

### ISSUE THREAD

**Issue by jaanos** [tinemakovecki/Drinks-and-things#2]
Trenutno imata v funkciji `insert_into_table` tako poizvedbo:

https://github.com/tinemakovecki/Drinks-and-things/blob/18f7924d2cd76855b3938ed31961483f3920a588/creating_database.py#L42-L47

To pomeni, da bosta sama morala skrbeti za ustrezno predstavitev podatkov, kar seveda lahko vodi do napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/) (pa tudi, če bosta to funkcijo uporabljala samo za uvoz podatkov, lahko pride do napak zaradi npr. navednic v nizih).

Za vstavljanje samih podatkov uporabita `%s` - nekako tako bi šlo:
```python
cur.execute("""
    INSERT INTO {} ({}) VALUES ({})
""".format(table_name, names, ", ".join(["%s"] * len(entry_values))), entry_values)
```
Seveda mora `entry_values` tukaj biti seznam ali nabor vaših vrednosti (takšnih tipov, kot so). Še lepše bi morda bilo, da funkcija kot argument dobi slovar (kjer so ključi imena stolpcev), pa potem sestavi ustrezne vrednosti za uporabo v poizvedbi.

Še to: opažam, da imata v tabeli `pijaca` stolpca `pivo_id` in `vino_id`, od katerih bo en vedno `NULL`. Namesto tega, da ima vsaka pijača dva ID-ja, svetujem, da ta dva stolpca odstranita, stolpca `id` v tabelah `pivo` in `vino` pa naj bosta tipa `INTEGER` in referenci na stolpec `id` v tabeli `pijaca`. Prav tako svetujem, da imata ID-je kot glavne ključe še za vrste hrane in pijače (imena so lahko `UNIQUE`, da se ne ponavljajo).

**Comment by tinemakovecki** [comment]
Način vstavljanja podatkov v bazo je bil popravljen in baza preoblikovana.
commit 80a231dff8b5c3d538ba8e45ef45eda234b871b9

**Comment by jaanos** [comment]
Še na to referenco bi opozoril:

https://github.com/tinemakovecki/Drinks-and-things/blob/e99b72a87125135ba2770c39ddb0490ede44a2f6/creating_database.py#L95

Seveda naj gre tukaj referenca na ID.
